version: "3.8"

services:
  booking-service-db:
    container_name: booking-service-db
    image: postgres:16.1
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_DATABASE=$POSTGRES_DATABASE
      - POSTGRES_USERNAME=$POSTGRES_USERNAME
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT

  app:
    container_name: app
    depends_on:
      - booking-service-db
    restart: on-failure
    build: .
    image: booking-service
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url" : "jdbc:postgresql://booking-service-db:$POSTGRES_LOCAL_PORT/$POSTGRES_DATABASE?createDatabaseIfNotExist=true",
             "spring.datasource.username" : "$POSTGRES_USERNAME",
             "spring.datasource.password" : "$POSTGRES_PASSWORD"
           }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
